# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('message_type', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
