# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20180417_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(),
        ),
    ]
